FROM node:25-alpine3.22 

WORKDIR /app

COPY package.json package-lock.json* ./

RUN --mount=type=cache,target=/root/.npm npm ci

COPY . .

EXPOSE 4200 49153

CMD ["npx","ng","serve","--host=0.0.0.0","--poll"]