services :
  backend:
    build:
      context: ./backend_py
      dockerfile: Dockerfile.dev
    ports:
    - "8000:8000"
    networks:
    - skull_group

    volumes: 
    - ./backend_py/app:/app/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
    - "4200:4200"
    - "49153:49153"

    networks:
    - skull_group

    volumes: 
    - ./frontend/src:/app/src

networks:
  skull_group:
    driver: bridge