FROM python:3.14

WORKDIR /app

COPY ./requirements.txt .

RUN pip install -r ./requirements.txt

COPY ./app .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--reload","--host","0.0.0.0","--port","8000"]
